quarkus.http.port=${AI_APP_PORT}

app.voyages.path=../data/voyages.csv


#quarkus.langchain4j.chat-model.provider = ${AI_MODEL_PROVIDER}
quarkus.langchain4j.chat-model.provider = openai
#quarkus.langchain4j.chat-model.provider = anthropic
#quarkus.langchain4j.chat-model.provider = ai-gemini

quarkus.langchain4j.log-requests = true
quarkus.langchain4j.log-responses = true

quarkus.langchain4j.guardrails.max-retries=0

# OpenAI Configuration
quarkus.langchain4j.openai.api-key = ${OPEN_AI_TOKEN}
quarkus.langchain4j.openai.timeout = 30s
#quarkus.langchain4j.openai.chat-model.model-name=gpt-4o-mini
quarkus.langchain4j.openai.chat-model.model-name=Nemotron-3-Nano-4B

# Local LLM, Nemotron (OpenAI-compatible configuration)
#quarkus.langchain4j.openai.base-url = http://localhost:30000/v1/
#quarkus.langchain4j.openai.api-key = ${OPEN_AI_TOKEN}
#quarkus.langchain4j.openai.timeout = 300s
#quarkus.langchain4j.openai.chat-model.model-name=Nemotron-3-Nano-4B

# Anthropic/Claude Configuration
quarkus.langchain4j.anthropic.api-key=${ANTHROPIC_AI_TOKEN}
quarkus.langchain4j.anthropic.timeout=30s
quarkus.langchain4j.anthropic.chat-model.model-name=claude-sonnet-4-6

# Google Gemini Configuration
quarkus.langchain4j.ai.gemini.api-key=${GOOGLE_AI_TOKEN}
quarkus.langchain4j.ai.gemini.timeout=30s
quarkus.langchain4j.ai.gemini.chat-model.model-name=gemini-2.0-flash
