### OUTPUT, 1
GET http://localhost:8080/api/lists/1

### OUTPUT, check memory 1/1
GET http://localhost:8080/api/lists/1/customers/1

### OUTPUT, 1/2
GET http://localhost:8080/api/lists/1/customers/2

### OUTPUT, 1/3
GET http://localhost:8080/api/lists/1/customers/3


### OUTPUT, 2
GET http://localhost:8080/api/lists/5

### OUTPUT, 2
GET http://localhost:8080/api/lists/99/customers/3